Repository Team-CMD/NowKick, pull requests merged in 2023-01, with the labels that each got.

#20 [Feature] 유저 정보 템플릿
  view/user_info.ejs
Labels: Front-End : Feature, Category : HTML

#21 기능 : 경기 정보 템플릿 view/match_info.ejs 추가
  view/match_info.ejs
Labels: Front-End : Feature, Category : HTML

#22 [Feature] 경기 참가자 정보 조회 & 경기 정보 API
  db/select_field.js
  db/select_match.js
  db/select_players_by_match.js
  lib/date.js
  main.js
  router/match.js
Labels: Category : JS, Back-End : Feature, Category : DB, Category : API

#24 [Feature] 유저 정보 API
  db/select_user.js
  main.js
  router/user.js
Labels: Category : JS, Back-End : Feature, Category : DB, Category : API

#28 [Feature] 경기 참여 신청 폼 원형 구현
  view/match_apply_form.html
Labels: Front-End : Feature, Category : Style, Category : HTML

#30 기능 : 경기 참여 신청 폼 템플릿 구현
  view/match_apply_form.ejs
Labels: Front-End : Feature, Category : HTML

#32 [Feature] 헤더 원형 구현
  view/header.html
Labels: Front-End : Feature, Category : Style, Category : HTML

#34 [Feature]헤더 템플릿 구현
  view/header.ejs
Labels: Front-End : Feature, Category : Style, Category : HTML

#36 [Feautre] 경기 목록 원형 구현
  view/match_list.html
Labels: Front-End : Feature, Category : Style, Category : HTML

#39 [Feature] 경기 정보 요약 템플릿 구현
  view/match_info_summary.ejs
Labels: Front-End : Feature, Category : HTML

#53 [Feature] 경기 참여 신청 - 유저 경기 참가 등록
  main.js
  router/match.js
Labels: Category : JS, Back-End : Feature, Category : DB, Category : API

#54 [Feature] 경기 참여 & 에러 페이지 & 경기 목록 페이지 & 템플릿 통합 & 경기 매칭
  db/init.sql
  db/insert_user.js
  db/select_match.js
  db/select_match_user.js
  db/select_user.js
  db/update_match_user.js
  main.js
  middleware/match_handler.js
  middleware/user_validator.js
  public/css/foot.css
  public/css/user_info.css
  router/match.js
  router/user.js
  view/match_apply_form.ejs
  view/match_info.ejs
  view/user_info.ejs
Labels: Front-End : Fix, Front-End : Feature, Category : Style, Category : HTML, Category : JS, Back-End : Feature, Category : DB, Category : API, Front-End : Refactor
